#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
test_root="$(mktemp -d "${TMPDIR:-/tmp}/test-update-tags.XXXXXX")"

cleanup() {
  rm -rf "${test_root}"
}
trap cleanup EXIT

mkdir -p "${test_root}/scripts" "${test_root}/_posts" "${test_root}/_data" "${test_root}/.githooks"
cp "${repo_root}/scripts/update-tags.sh" "${test_root}/scripts/update-tags.sh"
cp "${repo_root}/scripts/install-hooks.sh" "${test_root}/scripts/install-hooks.sh"
cp "${repo_root}/.githooks/pre-commit" "${test_root}/.githooks/pre-commit"
chmod +x "${test_root}/scripts/update-tags.sh" \
  "${test_root}/scripts/install-hooks.sh" \
  "${test_root}/.githooks/pre-commit"

write_post() {
  local path="$1"
  shift
  {
    echo '---'
    echo 'layout: post'
    echo 'tags:'
    while (($# > 0)); do
      printf '  - %s\n' "$1"
      shift
    done
    echo '---'
    echo 'Fixture.'
  } >"${path}"
}

assert_contains() {
  local path="$1"
  local expected="$2"
  if ! grep -Fq -- "${expected}" "${path}"; then
    echo "Expected ${path} to contain: ${expected}" >&2
    exit 1
  fi
}

assert_not_contains() {
  local path="$1"
  local unexpected="$2"
  if grep -Fq -- "${unexpected}" "${path}"; then
    echo "Expected ${path} not to contain: ${unexpected}" >&2
    exit 1
  fi
}

write_post "${test_root}/_posts/2026-01-01-one.md" 'shared' 'shared' 'singleton'
write_post "${test_root}/_posts/2026-01-02-two.md" 'shared' '"Alpha"' "'quoted value'"
write_post "${test_root}/_posts/2026-01-03-three.md" 'Alpha' "'quoted value'"

"${test_root}/scripts/update-tags.sh"
printf '%s\n' \
  '# Generated by scripts/update-tags.sh; do not edit manually.' \
  '# Only tags used by at least two distinct posts are listed.' \
  '- "Alpha"' \
  '- "quoted value"' \
  '- "shared"' >"${test_root}/expected-tags.yml"
cmp "${test_root}/expected-tags.yml" "${test_root}/_data/tags.yml"
assert_contains "${test_root}/_data/tags.yml" '- "Alpha"'
assert_contains "${test_root}/_data/tags.yml" '- "quoted value"'
assert_contains "${test_root}/_data/tags.yml" '- "shared"'
assert_not_contains "${test_root}/_data/tags.yml" 'singleton'

cp "${test_root}/_data/tags.yml" "${test_root}/first-tags.yml"
"${test_root}/scripts/update-tags.sh"
cmp "${test_root}/first-tags.yml" "${test_root}/_data/tags.yml"
"${test_root}/scripts/update-tags.sh" --check

echo '# stale marker' >>"${test_root}/_data/tags.yml"
if "${test_root}/scripts/update-tags.sh" --check >/dev/null 2>&1; then
  echo "Expected --check to detect stale output." >&2
  exit 1
fi
assert_contains "${test_root}/_data/tags.yml" '# stale marker'

write_post "${test_root}/_posts/2026-01-03-three.md" 'Alpha' "'quoted value'" 'singleton'
"${test_root}/scripts/update-tags.sh"
assert_contains "${test_root}/_data/tags.yml" '- "singleton"'

write_post "${test_root}/_posts/2026-01-03-three.md" 'Alpha'
"${test_root}/scripts/update-tags.sh"
assert_not_contains "${test_root}/_data/tags.yml" 'quoted value'
assert_not_contains "${test_root}/_data/tags.yml" 'singleton'

printf '%s\n' '---' 'layout: post' 'tags: [shared]' '---' >"${test_root}/_posts/2026-01-04-bad.md"
if "${test_root}/scripts/update-tags.sh" >/dev/null 2>&1; then
  echo "Expected malformed inline tags to fail." >&2
  exit 1
fi
rm "${test_root}/_posts/2026-01-04-bad.md"

git -C "${test_root}" init -q
git -C "${test_root}" config user.name 'Tag Test'
git -C "${test_root}" config user.email 'tag-test@example.invalid'
git -C "${test_root}" add .
git -C "${test_root}" commit -qm 'Initial fixtures'

write_post "${test_root}/_posts/2026-01-04-four.md" 'index-only'
write_post "${test_root}/_posts/2026-01-05-five.md" 'index-only'
git -C "${test_root}" add _posts
write_post "${test_root}/_posts/2026-01-04-four.md" 'unstaged-only'
write_post "${test_root}/_posts/2026-01-05-five.md" 'unstaged-only'

"${test_root}/scripts/install-hooks.sh"
if [[ "$(git -C "${test_root}" config --local --get core.hooksPath)" != ".githooks" ]]; then
  echo "Hook installer did not configure core.hooksPath." >&2
  exit 1
fi
"${test_root}/scripts/install-hooks.sh" >/dev/null

(
  cd "${test_root}"
  .githooks/pre-commit
)

git -C "${test_root}" show :_data/tags.yml >"${test_root}/staged-tags.yml"
assert_contains "${test_root}/staged-tags.yml" '- "index-only"'
assert_not_contains "${test_root}/staged-tags.yml" 'unstaged-only'

git -C "${test_root}" config --local core.hooksPath custom-hooks
if "${test_root}/scripts/install-hooks.sh" >/dev/null 2>&1; then
  echo "Expected hook installer to preserve a custom hooks path." >&2
  exit 1
fi

git -C "${test_root}" config --local --unset core.hooksPath
printf '%s\n' '#!/usr/bin/env bash' 'exit 0' >"${test_root}/.git/hooks/pre-commit"
chmod +x "${test_root}/.git/hooks/pre-commit"
if "${test_root}/scripts/install-hooks.sh" >/dev/null 2>&1; then
  echo "Expected hook installer to preserve an existing legacy hook." >&2
  exit 1
fi

echo "Tag generator and hook tests passed."
